package com.cg.ibs.cardmanagement.ui;

public enum CustomerMenu {
	LIST_EXISTING_DEBIT_CARDS, LIST_EXISTING_CREDIT_CARDS, APPLY_NEW_DEBIT_CARD, APPLY_NEW_CREDIT_CARD, UPGRADE_EXISTING_DEBIT_CARD, UPGRADE_EXISTING_CREDIT_CARD, RESET_DEBIT_CARD_PIN, RESET_CREDIT_CARD_PIN, REPORT_DEBIT_CARD_LOST, REPORT_CREDIT_CARD_LOST, REQUEST_DEBIT_CARD_STATEMENT, REQUEST_CREDIT_CARD_STATEMENT, REPORT_DEBITCARD_STATEMENT_MISMATCH, REPORT_CREDITCARD_STATEMENT_MISMATCH, CUSTOMER_LOG_OUT,VIEW_QUERY_STATUS;
}
